<?php

/**
 * Implements template_preprocess_page().
 */
function tailwindcss_preprocess_page(array &$variables): void {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  if ($route_name === 'entity.canvas_page.canonical' || str_starts_with($route_match->getRouteObject()?->getPath() ?? '', '/canvas/')) {
    $variables['rendered_by_canvas'] = TRUE;
  }
  elseif ($route_name === 'entity.node.canonical' && \Drupal::moduleHandler()->moduleExists('canvas')) {
    $node = $route_match->getParameter('node');

    // In some cases, the node parameter might not be upcast yet (it could just be a string/int ID).
    if (is_numeric($node) && !$node instanceof NodeInterface) {
      $node = \Drupal::entityTypeManager()->getStorage('node')->load($node);
    }

    if ($node instanceof NodeInterface) {
      try {
        $variables['rendered_by_canvas'] = (bool) \Drupal::entityTypeManager()
          ->getStorage('content_template')
          ->getQuery()
          ->accessCheck(FALSE)
          ->count()
          ->condition('content_entity_type_id', 'node')
          ->condition('content_entity_type_bundle', $node->getType())
          ->condition('content_entity_type_view_mode', 'full')
          ->condition('status', TRUE)
          ->execute();
      } catch (\Exception $e) {
        $variables['rendered_by_canvas'] = FALSE;
      }
    } else {
      $variables['rendered_by_canvas'] = FALSE;
    }
  }
  else {
    $variables['rendered_by_canvas'] = FALSE;
  }
}
